#!/bin/sh

# System Info
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].hostname='NanoPi-<model_name>'

# System Log
uci set system.@system[0].log_size='512'
uci set system.@system[0].log_ip='127.0.0.1'
uci set system.@system[0].log_proto='tcp'
uci set system.@system[0].log_file='/root/system.log'
uci set system.@system[0].conloglevel='8'
uci set system.@system[0].cronloglevel='5'
uci commit system

# Default theme
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# Feeds
sed -i 's,downloads.openwrt.org,mirrors.tuna.tsinghua.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

# uHTTPd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci set uhttpd.main.tcp_keepalive=0
uci set uhttpd.main.script_timeout=65535
uci set uhttpd.main.script_network_timeout=65535
uci commit uhttpd
/etc/init.d/uhttpd restart

# Close IPv6
uci delete network.globals.ula_prefix
uci delete network.lan.ip6assign
uci delete network.wan6
uci delete dhcp.lan.ra
uci delete dhcp.lan.ra_management
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ndp
uci set dhcp.@dnsmasq[0].filter_aaaa=1
uci commit dhcp

# Packet Steering
uci set network.globals.packet_steering=1

uci commit network
/etc/init.d/network restart

# Firewall
uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci commit firewall

# SSL
sed -i 's,#devcrypto,devcrypto,g' /etc/ssl/openssl.cnf
sed -i 's,#USE_SOFTDRIVERS = 2,USE_SOFTDRIVERS = 1,g' /etc/ssl/openssl.cnf

# Dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

# ShellClash
/etc/init.d/shellcrash disable

# Samba4
uci set samba4.@samba[0].interface='lan'
uci set samba4.@samba[0].macos='1'
uci set samba4.@samba[0].disable_netbios='1'
uci commit samba4

# Vim
sed -i 's/set mouse/"set mouse/g' /usr/share/vim/vim*/defaults.vim

# Others
[ ! -f '/usr/bin/ip' ] && [ -f '/sbin/ip' ] && ln -sf /sbin/ip /usr/bin/ip
[ ! -f '/usr/bin/wget-ssl' ] && [ -f '/usr/bin/wget' ] && ln -sf /usr/bin/wget /usr/bin/wget-ssl
[ ! -f '/usr/bin/vi' ] && [ -f '/usr/bin/vim' ] && ln -sf /usr/bin/vim /usr/bin/vi
sed -i "s_alias ll=.*_alias ll='ls -hlAF --color=auto'_g" /etc/shinit
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full
#sync; echo 3 > /proc/sys/vm/drop_caches

# Flush LuCI cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

# Private Settings
my_device='/dev/sda1'
my_dir='/mnt/share'
my_script="${my_dir}/init.sh"
if [ -b "${my_device}" ];then
    mkdir ${my_dir}
    mount ${my_device} ${my_dir}
    [ -f "${my_script}" ] && sh ${my_script}
fi

exit 0
