#!/bin/sh

# System Info
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].hostname='NanoPi-R2S'
uci commit system

# Default theme
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# Feeds
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

# uHTTPd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci set uhttpd.main.http_keepalive=0
uci set uhttpd.main.tcp_keepalive=0
uci set uhttpd.main.script_timeout=65535
uci set uhttpd.main.script_network_timeout=65535
uci commit uhttpd
/etc/init.d/uhttpd restart

# Close IPv6
uci delete network.globals.ula_prefix
uci delete network.lan.ip6assign
uci delete network.wan6
uci delete dhcp.lan.ra
uci delete dhcp.lan.ra_management
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ndp
uci commit dhcp

# Packet Steering
uci set network.globals.packet_steering=1
uci commit network
/etc/init.d/network restart

# Firewall
uci set firewall.@defaults[0].fullcone='1'
uci set firewall.@defaults[0].flow_offloading='0'
uci commit firewall

# SSL
sed -i 's,#devcrypto,devcrypto,g' /etc/ssl/openssl.cnf
sed -i 's,#USE_SOFTDRIVERS = 2,USE_SOFTDRIVERS = 1,g' /etc/ssl/openssl.cnf

# Dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

# Interfaces
ifdown wan && ifup wan
ifdown lan && ifup lan

# OpenClash
# uci set openclash.config.core_version='linux-armv8'
# #uci set openclash.config.en_mode='fake-ip'
# #uci set openclash.config.operation_mode='fake-ip'
# uci set openclash.config.log_level='info'
# uci commit openclash

# Vim
sed -i 's/set mouse/"set mouse/g' /usr/share/vim/vim82/defaults.vim

# Others
ln -sf /sbin/ip /usr/bin/ip
ln -sf /usr/bin/wget /usr/bin/wget-ssl
ln -sf /usr/bin/vim /usr/bin/vi
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full
#sync; echo 3 > /proc/sys/vm/drop_caches

# Flush LuCI cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
